### ISSUE TITLE
TypeError: Cannot destructure property `index` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by 001123** [codebandits/react-app-rewire-css-modules#4] opened 2017-12-11 09:44 UTC
I got error 

This is my overwrite config 

```jsx
/* config-overrides.js */
const {
  injectBabelPlugin
} = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');
const rewireCssModules = require('react-app-rewire-css-modules');

module.exports = function override(config, env) {
  config = rewireCssModules(config, env);
  //do stuff with the webpack config...
  config = injectBabelPlugin(['import', {
    libraryName: 'antd',
    style: true
  }], config); // change importing css to less

  config = rewireLess.withLoaderOptions({
    modifyVars: {
      "@primary-color": "#fa4169"
    },
  })(config, env);

  
  return config;
}
```

**Comment by horizon0514** [comment] 2017-12-14 02:42
I had the error too.
And if use Node v6.0 , it's OK.
I'm still working on it.

**Comment by skreborn** [comment] 2017-12-19 10:30
This seems to be solved by applying #2.

**Comment by horizon0514** [comment] 2017-12-20 02:22
@skreborn  it didn't work for me

**Comment by DBingo** [comment] 2017-12-25 06:57
@skreborn yeah, it can be solved. But the code is still waiting to be merged. I have to change the source code according to #2 . It's inconvenient.

**Comment by zzsoszz** [comment] 2018-01-03 04:08
i am waiting to be merged

**Comment by lnhrdt** [comment] 2018-01-28 00:22
Thank you @001123  for reporting this issue and to everyone else for commenting as well.

The fix in #2 has been merged. I only develop on *nix. Can someone test the latest version on Windows and report back if the issue is resolved for you?

**Comment by unconfident** [comment] 2018-01-28 04:06
Thank you for resolving this.

> Can someone test the latest version on Windows and report back if the issue is resolved for you?

Can confirm, it's fixed. Crashes on ce107750a3 (pre-patch), works as intended on 956a2330c2 (current).

**Closed** 2018-01-28 07:20 UTC

**Comment by tantaiMoon** [comment] 2018-08-21 01:55
How to solve this problem, I can't understand its final solution.
